### ISSUE TITLE
Feature Request - Tech Stack

### ISSUE THREAD

**Issue by captn3m0** [clearbit/clearbit-slack#15]
We would really benefit from knowing what the company's tech stack is.

**Comment by harlow** [comment]
@captn3m0 sorry for the tardy reply. Here is a post on our stack: http://stackshare.io/clearbit/scaling-clearbit-to-2m-api-requests-per-day

**Comment by harlow** [comment]
Think I might have misunderstood the request. We've also added Tech Tags to our company responses: http://blog.clearbit.com/tech-tags

**Comment by captn3m0** [comment]
Yes, but I meant that clearbit-slack should support posting the tech tags to slack.
